global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'task-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['task-service-task-service-1:8080', 'task-service-task-service-2:8080', 'task-service-task-service-3:8080']
